import { format } from 'date-fns';
import type { Message, ExportFormat, ExportOptions } from '@/types/chat';

export function formatMessageForExport(message: Message, options: ExportOptions): string {
  const timestamp = options.includeTimestamps 
    ? `[${format(new Date(message.created_at), 'MMM d, yyyy h:mm a')}] `
    : '';
  const role = message.role === 'user' ? 'You' : 'Assistant';
  return `${timestamp}${role}:\n${message.content}`;
}

export function exportMessages(
  messages: Message[],
  title: string,
  format: ExportFormat,
  options?: Partial<ExportOptions>
): string {
  const opts: ExportOptions = {
    format,
    includeTimestamps: true,
    includeMetadata: false,
    ...options
  };
  const exportDate = format(new Date(), 'MMM d, yyyy h:mm a');

  switch (format) {
    case 'json':
      return JSON.stringify({
        title,
        exportDate,
        messageCount: messages.length,
        options: opts,
        messages: messages.map(m => ({
          role: m.role,
          content: m.content,
          timestamp: m.created_at
        }))
      }, null, 2);
    case 'txt':
      return [
        `=== ${title} ===`,
        `Exported: ${exportDate}`,
        'Messages: ' + messages.length,
        '-'.repeat(50),
        '',
        ...messages.map(m => formatMessageForExport(m, opts)),
        '',
        '-'.repeat(50),
        `End of export - ${messages.length} messages`
      ].join('\n');
    case 'pdf':
      return generateHTMLExport(messages, title, exportDate, opts);
    default:
      return '';
  }
}

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c] || c));
}

function generateHTMLExport(messages: Message[], title: string, exportDate: string, options: ExportOptions): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; line-height: 1.6; color: #333; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 30px; }
    .message { margin-bottom: 20px; padding: 15px 20px; border-radius: 8px; }
    .user { background-color: #e3f2fd; margin-left: 5%; }
    .assistant { background-color: #f5f5f5; margin-right: 5%; }
    .role { font-weight: 600; margin-bottom: 8px; }
    .content { white-space: pre-wrap; }
    .timestamp { font-size: 0.8em; color: #999; margin-top: 8px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 0.85em; text-align: center; }
    code { background-color: #f0f0f0; padding: 2px 6px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">Exported: ${exportDate} | Messages: ${messages.length}</p>
  ${messages.map(m => `
  <div class="message ${m.role}">
    <div class="role">${m.role === 'user' ? 'You' : 'KCA Connect AI'}</div>
    <div class="content">${escapeHtml(m.content)}</div>
    ${options.includeTimestamps ? `<div class="timestamp">${format(new Date(m.created_at), 'MMM d, yyyy h:mm a')}</div>` : ''}
  </div>`).join('')}
  <div class="footer">Generated by KCA Connect AI | ${messages.length} messages | ${exportDate}</div>
</body>
</html>`;
}

export function downloadExport(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try { await navigator.clipboard.writeText(text); return true; } 
  catch { return false; }
}

export function getMimeType(format: ExportFormat): string {
  switch (format) {
    case 'json': return 'application/json';
    case 'txt': return 'text/plain';
    case 'pdf': return 'text/html';
    default: return 'text/plain';
  }
}

export function getFileExtension(format: ExportFormat): string {
  switch (format) {
    case 'json': return 'json';
    case 'txt': return 'txt';
    case 'pdf': return 'html';
    default: return 'txt';
  }
}
