import React, { useState } from 'react';
import { useChat } from '@/contexts/ChatContext';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { 
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Download, FileJson, FileText, FileType, Copy, Check } from 'lucide-react';
import { format } from 'date-fns';
import type { ExportFormat } from '@/types/chat';
import { cn } from '@/lib/utils';

interface ExportChatProps {
  children?: React.ReactNode;
}

export function ExportChat({ children }: ExportChatProps) {
  const { messages, currentConversation } = useChat();
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'MMM d, yyyy h:mm a');
  };

  const generateExportContent = (format: ExportFormat): string => {
    const title = currentConversation?.title || 'Chat Export';
    const date = formatDate(new Date().toISOString());

    switch (format) {
      case 'json':
        return JSON.stringify({
          title,
          exportDate: date,
          messages: messages.map(m => ({
            role: m.role,
            content: m.content,
            timestamp: m.created_at
          }))
        }, null, 2);

      case 'txt':
        const txtLines = [
          `=== ${title} ===`,
          `Exported: ${date}`,
          '─'.repeat(50),
          '',
          ...messages.map(m => {
            const timestamp = formatDate(m.created_at);
            return `[${timestamp}] ${m.role.toUpperCase()}:\n${m.content}\n`;
          }),
          '',
          '─'.repeat(50),
          `End of export - Generated by KCA Connect AI`
        ];
        return txtLines.join('\n');

      case 'pdf':
        // For PDF, we return a formatted HTML that can be used with jsPDF
        return `
<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 20px; }
    .message { margin-bottom: 15px; padding: 10px; border-radius: 5px; }
    .user { background-color: #e3f2fd; margin-left: 20%; }
    .assistant { background-color: #f5f5f5; margin-right: 20%; }
    .role { font-weight: bold; margin-bottom: 5px; }
    .content { white-space: pre-wrap; }
    .timestamp { font-size: 0.8em; color: #999; margin-top: 5px; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">Exported: ${date}</p>
  ${messages.map(m => `
  <div class="message ${m.role}">
    <div class="role">${m.role === 'user' ? 'You' : 'KCA Connect AI'}</div>
    <div class="content">${m.content}</div>
    <div class="timestamp">${formatDate(m.created_at)}</div>
  </div>
  `).join('')}
</body>
</html>
        `;

      default:
        return '';
    }
  };

  const handleDownload = (format: ExportFormat) => {
    const content = generateExportContent(format);
    const blob = new Blob([content], { 
      type: format === 'json' ? 'application/json' 
          : format === 'txt' ? 'text/plain' 
          : 'text/html' 
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentConversation?.title || 'chat'}-export.${format === 'pdf' ? 'html' : format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const handleCopyToClipboard = async () => {
    const text = generateExportContent('txt');
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  return (
    <>
      {children ? (
        <div onClick={() => setIsOpen(true)}>{children}</div>
      ) : (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon">
              <Download className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => handleDownload('txt')}>
              <FileText className="h-4 w-4 mr-2" />
              Export as Text
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => handleDownload('json')}>
              <FileJson className="h-4 w-4 mr-2" />
              Export as JSON
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => handleDownload('pdf')}>
              <FileType className="h-4 w-4 mr-2" />
              Export as HTML/PDF
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleCopyToClipboard}>
              {copied ? (
                <>
                  <Check className="h-4 w-4 mr-2 text-green-500" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 mr-2" />
                  Copy to Clipboard
                </>
              )}
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )}

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Export Chat</DialogTitle>
            <DialogDescription>
              Choose a format to export your conversation
            </DialogDescription>
          </DialogHeader>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 py-4">
            <button
              onClick={() => handleDownload('txt')}
              className="flex flex-col items-center gap-2 p-4 rounded-lg border border-border hover:bg-accent transition-colors"
            >
              <FileText className="h-8 w-8 text-primary" />
              <span className="text-sm font-medium">Plain Text</span>
              <span className="text-xs text-muted-foreground">.txt file</span>
            </button>

            <button
              onClick={() => handleDownload('json')}
              className="flex flex-col items-center gap-2 p-4 rounded-lg border border-border hover:bg-accent transition-colors"
            >
              <FileJson className="h-8 w-8 text-primary" />
              <span className="text-sm font-medium">JSON</span>
              <span className="text-xs text-muted-foreground">.json file</span>
            </button>

            <button
              onClick={() => handleDownload('pdf')}
              className="flex flex-col items-center gap-2 p-4 rounded-lg border border-border hover:bg-accent transition-colors"
            >
              <FileType className="h-8 w-8 text-primary" />
              <span className="text-sm font-medium">HTML/PDF</span>
              <span className="text-xs text-muted-foreground">.html file</span>
            </button>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={handleCopyToClipboard}>
              {copied ? (
                <>
                  <Check className="h-4 w-4 mr-2 text-green-500" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 mr-2" />
                  Copy All
                </>
              )}
            </Button>
            <Button variant="outline" onClick={() => setIsOpen(false)}>
              Cancel
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

export default ExportChat;

